pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
    plugins {
        id 'com.android.application' version '9.3.1' apply false
        id 'com.android.library'    version '9.3.1' apply false
    }
}
include ':example-app', ':backtrace-library', ':coroner-client', ':gson'
