name: Upload Archives

on:
 push:
   tags: '[0-9]+.[0-9]+.[0-9]+*'
 workflow_dispatch:

jobs:
 build:
   env: 
     ANDROID_API_LEVEL: 23
     ANDROID_EMULATOR_LEVEL: 23
     ANDROID_BUILD_TOOLS_VERSION: 28.0.3
     ANDROID_TAG: google_apis
     ADB_INSTALL_TIMEOUT: 20

   runs-on: ubuntu-latest

   steps:
   - name: Checkout submodules
     uses: actions/checkout@v4
     with:
       fetch-depth: 2
       submodules: recursive
       token: ${{ secrets.ACCESS_TOKEN }}
       persist-credentials: false

   - name: set up JDK 17
     uses: actions/setup-java@v4
     with:
       java-version: 17.0.10
       distribution: "adopt"
       cache: gradle

   - name: PWD
     run: pwd

   - name: Add Maven credentials to gradle.properties
##     run: echo "NEXUS_USERNAME=${{ secrets.NEXUS_USERNAME }}" >> gradle.properties && echo "NEXUS_PASSWORD=${{ secrets.NEXUS_PASSWORD }}" >> gradle.properties
     run: echo "mavenCentralUsername=${{ secrets.OSSRH_USERNAME }}" && echo "mavenCentralPassword=${{ secrets.OSSRH_PASSWORD }}" && echo "signing.keyId=${{ secrets.SIGNING_KEY_ID }}" >> gradle.properties && echo "signing.password=${{ secrets.SIGNING_PASSWORD }}" >> gradle.properties  && echo "signing.secretKeyRingFile=secret_key.gpg" >> gradle.properties

   - name: LS
     run: ls
   - name: Prepare signing secret key ring file
     run: echo "${{ secrets.SIGNING_KEY }}" | base64 --decode > backtrace-library/secret_key.gpg

   - name: Grant execute permission for gradlew
     run: chmod +x gradlew

   - name: PWD
     run: pwd
   - name: LS
     run: ls
   - name: Upload archives
     run: ./gradlew publishAllPublicationsToMavenCentralRepository
     #     env:
#       ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ASCII_ARMORED_GPG_KEY }} # ASCII-armored GPG key
#       ORG_GRADLE_PROJECT_signingPassword: "" # Using empty password for GPG key
     env:
#       OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
#       OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
#       ORG_GRADLE_PROJECT_signing.keyId: ${{ secrets.SIGNING_KEY_ID }}
#       ORG_GRADLE_PROJECT_signing.key: ${{ secrets.SIGNING_KEY }}
#       ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
#       ORG_GRADLE_PROJECT_signing.password: ${{ secrets.SIGNING_PASSWORD }}
#       ORG_GRADLE_PROJECT_signingPassword:  ${{ secrets.SIGNING_PASSWORD }}
#       ORG_GRADLE_PROJECT_signing.secretKeyRingFile: ./secret_key.gpg

   - uses: xresloader/upload-to-github-release@v1
     env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     with:
       file: "example-app/build/outputs/native-debug-symbols/release/native-debug-symbols.zip;example-app/build/outputs/apk/debug/example-app-debug.apk"
       draft: true
       verbose: env.ACTIONS_STEP_DEBUG
